In [1]:
import torch

In [ ]:
a = torch.arange(1., 6.)
k = 2

torch.topk(a, k).values, torch.topk(a, k).indices

(tensor(4.), tensor([4, 3]))

In [10]:
torch.topk(a, k).values[0]=1

In [16]:
int(torch.topk(a, k).values[0])

5

In [12]:
sum(torch.topk(a, k).values)

tensor(9.)

In [66]:
a = torch.rand(((2, 5, 4)))
a

tensor([[[0.7409, 0.2033, 0.9909, 0.8236],
         [0.6404, 0.8165, 0.2285, 0.9542],
         [0.4167, 0.3685, 0.7415, 0.8287],
         [0.2220, 0.5589, 0.2310, 0.0971],
         [0.9943, 0.9097, 0.1291, 0.8356]],

        [[0.8047, 0.3422, 0.8618, 0.5717],
         [0.2022, 0.6414, 0.4011, 0.2690],
         [0.6357, 0.6724, 0.6700, 0.8491],
         [0.8685, 0.1948, 0.9003, 0.2837],
         [0.8013, 0.1548, 0.8626, 0.0168]]])

In [67]:
torch.topk(a,2,-1).values.shape, torch.topk(a,2,-1).indices.shape

(torch.Size([2, 5, 2]), torch.Size([2, 5, 2]))

In [68]:
indices = torch.topk(a,2,-1).indices

indices

tensor([[[2, 3],
         [3, 1],
         [3, 2],
         [1, 2],
         [0, 1]],

        [[2, 0],
         [1, 2],
         [3, 1],
         [2, 0],
         [2, 0]]])

In [69]:
torch.topk(a,2,-1).values / torch.sum(torch.topk(a,2,-1).values, dim=-1, keepdim=True)

tensor([[[0.5461, 0.4539],
         [0.5389, 0.4611],
         [0.5278, 0.4722],
         [0.7075, 0.2925],
         [0.5222, 0.4778]],

        [[0.5171, 0.4829],
         [0.6153, 0.3847],
         [0.5581, 0.4419],
         [0.5090, 0.4910],
         [0.5184, 0.4816]]])

In [ ]:
torch.topk(a,2,-1).indices[]

tensor([[[1, 7],
         [0, 2],
         [6, 3],
         [7, 4],
         [0, 2],
         [2, 5],
         [4, 0],
         [4, 1],
         [2, 6],
         [0, 7]]])

In [43]:
b = torch.randint(10,(1, 3, 2))
b

tensor([[[4, 1],
         [6, 3],
         [5, 7]]])

In [44]:
c = torch.randint(10,(1, 3, 2))
c

tensor([[[9, 3],
         [0, 5],
         [7, 1]]])

In [54]:
torch.sum([a,b], dim=-1, keepdim=True)

TypeError: sum() received an invalid combination of arguments - got (list, dim=int, keepdim=bool), but expected one of:
 * (Tensor input, *, torch.dtype dtype = None)
      didn't match because some of the keywords were incorrect: dim, keepdim
 * (Tensor input, tuple of ints dim, bool keepdim = False, *, torch.dtype dtype = None, Tensor out = None)
 * (Tensor input, tuple of names dim, bool keepdim = False, *, torch.dtype dtype = None, Tensor out = None)
