In [1]:
import torch

In [ ]:
a = torch.arange(1., 6.)
k = 2

torch.topk(a, k).values, torch.topk(a, k).indices

(tensor(4.), tensor([4, 3]))

In [10]:
torch.topk(a, k).values[0]=1

In [16]:
int(torch.topk(a, k).values[0])

5

In [12]:
sum(torch.topk(a, k).values)

tensor(9.)

In [66]:
a = torch.rand(((2, 5, 4)))
a

tensor([[[0.7409, 0.2033, 0.9909, 0.8236],
         [0.6404, 0.8165, 0.2285, 0.9542],
         [0.4167, 0.3685, 0.7415, 0.8287],
         [0.2220, 0.5589, 0.2310, 0.0971],
         [0.9943, 0.9097, 0.1291, 0.8356]],

        [[0.8047, 0.3422, 0.8618, 0.5717],
         [0.2022, 0.6414, 0.4011, 0.2690],
         [0.6357, 0.6724, 0.6700, 0.8491],
         [0.8685, 0.1948, 0.9003, 0.2837],
         [0.8013, 0.1548, 0.8626, 0.0168]]])

In [67]:
torch.topk(a,2,-1).values.shape, torch.topk(a,2,-1).indices.shape

(torch.Size([2, 5, 2]), torch.Size([2, 5, 2]))

In [68]:
indices = torch.topk(a,2,-1).indices

indices

tensor([[[2, 3],
         [3, 1],
         [3, 2],
         [1, 2],
         [0, 1]],

        [[2, 0],
         [1, 2],
         [3, 1],
         [2, 0],
         [2, 0]]])

In [69]:
torch.topk(a,2,-1).values / torch.sum(torch.topk(a,2,-1).values, dim=-1, keepdim=True)

tensor([[[0.5461, 0.4539],
         [0.5389, 0.4611],
         [0.5278, 0.4722],
         [0.7075, 0.2925],
         [0.5222, 0.4778]],

        [[0.5171, 0.4829],
         [0.6153, 0.3847],
         [0.5581, 0.4419],
         [0.5090, 0.4910],
         [0.5184, 0.4816]]])

In [ ]:
torch.topk(a,2,-1).indices[]

tensor([[[1, 7],
         [0, 2],
         [6, 3],
         [7, 4],
         [0, 2],
         [2, 5],
         [4, 0],
         [4, 1],
         [2, 6],
         [0, 7]]])

In [43]:
b = torch.randint(10,(1, 3, 2))
b

tensor([[[4, 1],
         [6, 3],
         [5, 7]]])

In [44]:
c = torch.randint(10,(1, 3, 2))
c

tensor([[[9, 3],
         [0, 5],
         [7, 1]]])

In [54]:
torch.sum([a,b], dim=-1, keepdim=True)

TypeError: sum() received an invalid combination of arguments - got (list, dim=int, keepdim=bool), but expected one of:
 * (Tensor input, *, torch.dtype dtype = None)
      didn't match because some of the keywords were incorrect: dim, keepdim
 * (Tensor input, tuple of ints dim, bool keepdim = False, *, torch.dtype dtype = None, Tensor out = None)
 * (Tensor input, tuple of names dim, bool keepdim = False, *, torch.dtype dtype = None, Tensor out = None)


In [124]:
d_model: int = 256
hidden_dim: int = 512
n_layers: int = 4
n_heads: int = 4
vocab_size: int = 10_000

num_experts: int = 8
num_shared_experts: int = 1
top_k: int = 2

n_kv_heads: int = 2
max_seq_len: int =  1024
rope_theta: float = 10_000.0

dk = d_model // n_heads

pairs = torch.arange(0, dk/2)
frequencies = 1/rope_theta**(2 * pairs / dk)

positions = torch.arange(max_seq_len, dtype=torch.float32)

angles = positions.view(len(positions), 1).contiguous() @ frequencies.view(1, len(frequencies)).contiguous()

angles = angles.repeat_interleave(2, dim=-1)

In [125]:
a.repeat_interleave(2,dim=0)

tensor([[[0.7409, 0.2033, 0.9909, 0.8236],
         [0.6404, 0.8165, 0.2285, 0.9542],
         [0.4167, 0.3685, 0.7415, 0.8287],
         [0.2220, 0.5589, 0.2310, 0.0971],
         [0.9943, 0.9097, 0.1291, 0.8356]],

        [[0.7409, 0.2033, 0.9909, 0.8236],
         [0.6404, 0.8165, 0.2285, 0.9542],
         [0.4167, 0.3685, 0.7415, 0.8287],
         [0.2220, 0.5589, 0.2310, 0.0971],
         [0.9943, 0.9097, 0.1291, 0.8356]],

        [[0.8047, 0.3422, 0.8618, 0.5717],
         [0.2022, 0.6414, 0.4011, 0.2690],
         [0.6357, 0.6724, 0.6700, 0.8491],
         [0.8685, 0.1948, 0.9003, 0.2837],
         [0.8013, 0.1548, 0.8626, 0.0168]],

        [[0.8047, 0.3422, 0.8618, 0.5717],
         [0.2022, 0.6414, 0.4011, 0.2690],
         [0.6357, 0.6724, 0.6700, 0.8491],
         [0.8685, 0.1948, 0.9003, 0.2837],
         [0.8013, 0.1548, 0.8626, 0.0168]]])

In [126]:
angles

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.0000e+00, 1.0000e+00, 7.4989e-01,  ..., 1.7783e-04, 1.3335e-04,
         1.3335e-04],
        [2.0000e+00, 2.0000e+00, 1.4998e+00,  ..., 3.5566e-04, 2.6670e-04,
         2.6670e-04],
        ...,
        [1.0210e+03, 1.0210e+03, 7.6564e+02,  ..., 1.8156e-01, 1.3615e-01,
         1.3615e-01],
        [1.0220e+03, 1.0220e+03, 7.6639e+02,  ..., 1.8174e-01, 1.3629e-01,
         1.3629e-01],
        [1.0230e+03, 1.0230e+03, 7.6714e+02,  ..., 1.8192e-01, 1.3642e-01,
         1.3642e-01]])

In [161]:
a = torch.randint(10, (10, 2))
b = torch.randint(10, (10, 2))

In [162]:
a

tensor([[1, 4],
        [9, 1],
        [7, 4],
        [2, 3],
        [8, 7],
        [0, 3],
        [3, 7],
        [6, 5],
        [5, 2],
        [2, 0]])

In [163]:
b

tensor([[0, 9],
        [8, 3],
        [9, 5],
        [0, 8],
        [1, 4],
        [6, 6],
        [4, 5],
        [5, 5],
        [1, 9],
        [2, 3]])

In [164]:
row, ind = torch.where(a==2)

In [165]:
row, ind

(tensor([3, 8, 9]), tensor([0, 1, 0]))

In [169]:
b[row,ind].unsqueeze(-1)

tensor([[0],
        [9],
        [2]])