In [1]:
import torch

In [ ]:
a = torch.arange(1., 6.)
k = 2

torch.topk(a, k).values, torch.topk(a, k).indices

(tensor(4.), tensor([4, 3]))

In [10]:
torch.topk(a, k).values[0]=1

In [16]:
int(torch.topk(a, k).values[0])

5

In [12]:
sum(torch.topk(a, k).values)

tensor(9.)

In [66]:
a = torch.rand(((2, 5, 4)))
a

tensor([[[0.7409, 0.2033, 0.9909, 0.8236],
         [0.6404, 0.8165, 0.2285, 0.9542],
         [0.4167, 0.3685, 0.7415, 0.8287],
         [0.2220, 0.5589, 0.2310, 0.0971],
         [0.9943, 0.9097, 0.1291, 0.8356]],

        [[0.8047, 0.3422, 0.8618, 0.5717],
         [0.2022, 0.6414, 0.4011, 0.2690],
         [0.6357, 0.6724, 0.6700, 0.8491],
         [0.8685, 0.1948, 0.9003, 0.2837],
         [0.8013, 0.1548, 0.8626, 0.0168]]])

In [67]:
torch.topk(a,2,-1).values.shape, torch.topk(a,2,-1).indices.shape

(torch.Size([2, 5, 2]), torch.Size([2, 5, 2]))

In [68]:
indices = torch.topk(a,2,-1).indices

indices

tensor([[[2, 3],
         [3, 1],
         [3, 2],
         [1, 2],
         [0, 1]],

        [[2, 0],
         [1, 2],
         [3, 1],
         [2, 0],
         [2, 0]]])

In [69]:
torch.topk(a,2,-1).values / torch.sum(torch.topk(a,2,-1).values, dim=-1, keepdim=True)

tensor([[[0.5461, 0.4539],
         [0.5389, 0.4611],
         [0.5278, 0.4722],
         [0.7075, 0.2925],
         [0.5222, 0.4778]],

        [[0.5171, 0.4829],
         [0.6153, 0.3847],
         [0.5581, 0.4419],
         [0.5090, 0.4910],
         [0.5184, 0.4816]]])

In [ ]:
torch.topk(a,2,-1).indices[]

tensor([[[1, 7],
         [0, 2],
         [6, 3],
         [7, 4],
         [0, 2],
         [2, 5],
         [4, 0],
         [4, 1],
         [2, 6],
         [0, 7]]])

In [43]:
b = torch.randint(10,(1, 3, 2))
b

tensor([[[4, 1],
         [6, 3],
         [5, 7]]])

In [44]:
c = torch.randint(10,(1, 3, 2))
c

tensor([[[9, 3],
         [0, 5],
         [7, 1]]])

In [54]:
torch.sum([a,b], dim=-1, keepdim=True)

TypeError: sum() received an invalid combination of arguments - got (list, dim=int, keepdim=bool), but expected one of:
 * (Tensor input, *, torch.dtype dtype = None)
      didn't match because some of the keywords were incorrect: dim, keepdim
 * (Tensor input, tuple of ints dim, bool keepdim = False, *, torch.dtype dtype = None, Tensor out = None)
 * (Tensor input, tuple of names dim, bool keepdim = False, *, torch.dtype dtype = None, Tensor out = None)


In [124]:
d_model: int = 256
hidden_dim: int = 512
n_layers: int = 4
n_heads: int = 4
vocab_size: int = 10_000

num_experts: int = 8
num_shared_experts: int = 1
top_k: int = 2

n_kv_heads: int = 2
max_seq_len: int =  1024
rope_theta: float = 10_000.0

dk = d_model // n_heads

pairs = torch.arange(0, dk/2)
frequencies = 1/rope_theta**(2 * pairs / dk)

positions = torch.arange(max_seq_len, dtype=torch.float32)

angles = positions.view(len(positions), 1).contiguous() @ frequencies.view(1, len(frequencies)).contiguous()

angles = angles.repeat_interleave(2, dim=-1)

In [125]:
a.repeat_interleave(2,dim=0)

tensor([[[0.7409, 0.2033, 0.9909, 0.8236],
         [0.6404, 0.8165, 0.2285, 0.9542],
         [0.4167, 0.3685, 0.7415, 0.8287],
         [0.2220, 0.5589, 0.2310, 0.0971],
         [0.9943, 0.9097, 0.1291, 0.8356]],

        [[0.7409, 0.2033, 0.9909, 0.8236],
         [0.6404, 0.8165, 0.2285, 0.9542],
         [0.4167, 0.3685, 0.7415, 0.8287],
         [0.2220, 0.5589, 0.2310, 0.0971],
         [0.9943, 0.9097, 0.1291, 0.8356]],

        [[0.8047, 0.3422, 0.8618, 0.5717],
         [0.2022, 0.6414, 0.4011, 0.2690],
         [0.6357, 0.6724, 0.6700, 0.8491],
         [0.8685, 0.1948, 0.9003, 0.2837],
         [0.8013, 0.1548, 0.8626, 0.0168]],

        [[0.8047, 0.3422, 0.8618, 0.5717],
         [0.2022, 0.6414, 0.4011, 0.2690],
         [0.6357, 0.6724, 0.6700, 0.8491],
         [0.8685, 0.1948, 0.9003, 0.2837],
         [0.8013, 0.1548, 0.8626, 0.0168]]])

In [126]:
angles

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.0000e+00, 1.0000e+00, 7.4989e-01,  ..., 1.7783e-04, 1.3335e-04,
         1.3335e-04],
        [2.0000e+00, 2.0000e+00, 1.4998e+00,  ..., 3.5566e-04, 2.6670e-04,
         2.6670e-04],
        ...,
        [1.0210e+03, 1.0210e+03, 7.6564e+02,  ..., 1.8156e-01, 1.3615e-01,
         1.3615e-01],
        [1.0220e+03, 1.0220e+03, 7.6639e+02,  ..., 1.8174e-01, 1.3629e-01,
         1.3629e-01],
        [1.0230e+03, 1.0230e+03, 7.6714e+02,  ..., 1.8192e-01, 1.3642e-01,
         1.3642e-01]])

In [161]:
a = torch.randint(10, (10, 2))
b = torch.randint(10, (10, 2))

In [162]:
a

tensor([[1, 4],
        [9, 1],
        [7, 4],
        [2, 3],
        [8, 7],
        [0, 3],
        [3, 7],
        [6, 5],
        [5, 2],
        [2, 0]])

In [163]:
b

tensor([[0, 9],
        [8, 3],
        [9, 5],
        [0, 8],
        [1, 4],
        [6, 6],
        [4, 5],
        [5, 5],
        [1, 9],
        [2, 3]])

In [164]:
row, ind = torch.where(a==2)

In [165]:
row, ind

(tensor([3, 8, 9]), tensor([0, 1, 0]))

In [169]:
b[row,ind].unsqueeze(-1)

tensor([[0],
        [9],
        [2]])

In [2]:
from src.model import Transformer
from src.config import ModelArgs

In [3]:
args = ModelArgs(
    d_model=64,           
    hidden_dim=128,       
    n_layers=2,         
    n_heads=4,       
    n_kv_heads=2,        
    vocab_size=1000, 
    max_seq_len=128,  
    num_experts=4,  
    num_shared_experts=1,
    top_k=2,
    batch_size=2 
)

model = Transformer(args)
model.eval() 
print("Model Initialized. Params:", sum(p.numel() for p in model.parameters()))

curr_seq_len = 20
x = torch.randint(args.vocab_size, (args.batch_size, curr_seq_len))

op, router_logits = model(x)


assert len(router_logits) == args.n_layers
assert router_logits[0].size() == (args.batch_size,curr_seq_len,args.num_experts)
assert op.size() == (args.batch_size, curr_seq_len, args.vocab_size)

print("All Assertions Passed")

Model Initialized. Params: 335168
All Assertions Passed


In [4]:
temp = 0

torch.manual_seed(42)
op1 = model.generate(x, max_new_tokens = 10, temperature = temp, use_kv_cache = True)

torch.manual_seed(42)
op2 = model.generate(x, max_new_tokens = 10, temperature = temp, use_kv_cache = False)


torch.equal(op1, op2)

True

In [5]:
op1

tensor([[378,   4, 186, 751,  70,   6, 721, 804, 281, 422, 768, 619,   3, 335,
         333, 313, 984, 108,  66, 248, 739, 522, 724, 744, 609, 435, 567, 766,
         865, 965],
        [320, 143, 252, 881, 206, 174,  58, 525, 993, 877, 735,   4, 530, 804,
         310, 261, 884, 814, 161, 899, 776, 112, 262, 599, 618, 592, 263, 412,
         344, 729]])

In [6]:
op2

tensor([[378,   4, 186, 751,  70,   6, 721, 804, 281, 422, 768, 619,   3, 335,
         333, 313, 984, 108,  66, 248, 739, 522, 724, 744, 609, 435, 567, 766,
         865, 965],
        [320, 143, 252, 881, 206, 174,  58, 525, 993, 877, 735,   4, 530, 804,
         310, 261, 884, 814, 161, 899, 776, 112, 262, 599, 618, 592, 263, 412,
         344, 729]])

In [7]:
# 1. Create a dummy input
x_test = torch.randint(0, 1000, (1, 20)) # Batch 1, Seq 20

# 2. Run Forward with Cache=False (The "Ground Truth")
logits_slow, _ = model(x_test, use_kv_cache=False)

# 3. Run Forward with Cache=True (The "Suspect")
# Note: We manually clear cache first just in case
model.layers[0].attention.k_cache.zero_()
model.layers[0].attention.v_cache.zero_()
logits_fast, _ = model(x_test, use_kv_cache=True)

# 4. Measure the difference
diff = (logits_slow - logits_fast).abs().max().item()
print(f"Max Logit Difference: {diff}")

Max Logit Difference: 0.0


In [8]:
# Create a dummy input (Batch 1, Seq 20)
x_test = torch.randint(0, 1000, (1, 20))

# 1. Run Slow Mode (Capture Layer 0 Attention Output)
model.zero_grad()
for layer in model.layers:
    layer.attention.k_cache.zero_()
    layer.attention.v_cache.zero_()

# Hook to capture output
slow_attn_out = []
def hook_slow(module, input, output):
    slow_attn_out.append(output)

# Register hook on Layer 0 Attention
handle = model.layers[0].attention.register_forward_hook(hook_slow)
logits_slow, _ = model(x_test, use_kv_cache=False)
handle.remove()

# 2. Run Fast Mode (Capture Layer 0 Attention Output)
# Force prefill logic by just running it once with use_kv_cache=True
model.zero_grad()
for layer in model.layers:
    layer.attention.k_cache.zero_()
    layer.attention.v_cache.zero_()

fast_attn_out = []
def hook_fast(module, input, output):
    fast_attn_out.append(output)

handle = model.layers[0].attention.register_forward_hook(hook_fast)
logits_fast, _ = model(x_test, use_kv_cache=True)
handle.remove()

# 3. Compare
diff = (slow_attn_out[0] - fast_attn_out[0]).abs().max().item()
print(f"Attention Layer Diff: {diff}")

if diff < 1e-4:
    print("SUCCESS: Your Logic is Correct. The 8.24 diff is just MoE Router chaos.")
else:
    print("FAILURE: Your KV Cache Logic has a bug.")

Attention Layer Diff: 0.0
SUCCESS: Your Logic is Correct. The 8.24 diff is just MoE Router chaos.


In [9]:
import torch

@torch.no_grad()
def reset_kv_cache(model):
    for layer in model.layers:
        layer.attention.k_cache.zero_()
        layer.attention.v_cache.zero_()

@torch.no_grad()
def kv_cache_logit_check(model, vocab_size=1000, prompt_len=20, max_new=10, device="cpu"):
    model.eval()
    model.to(device)

    x = torch.randint(0, vocab_size, (1, prompt_len), device=device)

    # Prefill cache with full prompt (fast path)
    reset_kv_cache(model)
    _ = model(x, start_posn=0, use_kv_cache=True)

    for t in range(max_new):
        # Slow: full context logits for next token
        slow_logits, _ = model(x, start_posn=0, use_kv_cache=False)
        slow_next = slow_logits[:, -1, :]

        # Fast: cached incremental logits for next token (feed last token only)
        start_posn = x.shape[1] - 1
        fast_logits, _ = model(x[:, -1:], start_posn=start_posn, use_kv_cache=True)
        fast_next = fast_logits[:, -1, :]

        diff = (slow_next - fast_next).abs().max().item()
        print(f"step {t}: max|diff| = {diff}")

        assert torch.allclose(slow_next, fast_next, rtol=1e-4, atol=1e-4), "KV-cache mismatch"

        # Deterministic extension (greedy)
        x = torch.cat([x, slow_next.argmax(dim=-1, keepdim=True)], dim=1)

    print("KV-cache logits match.")

# usage
kv_cache_logit_check(model, vocab_size=args.vocab_size, prompt_len=20, max_new=10, device="cpu")


step 0: max|diff| = 6.109476089477539e-07
step 1: max|diff| = 2.682209014892578e-07
step 2: max|diff| = 2.682209014892578e-07
step 3: max|diff| = 3.5762786865234375e-07
step 4: max|diff| = 4.544854164123535e-07
step 5: max|diff| = 4.470348358154297e-07
step 6: max|diff| = 3.427267074584961e-07
step 7: max|diff| = 5.029141902923584e-07
step 8: max|diff| = 3.8743019104003906e-07
step 9: max|diff| = 6.854534149169922e-07
KV-cache logits match.


In [10]:
import torch

@torch.no_grad()
def zero_all_caches(model):
    for layer in model.layers:
        layer.attention.k_cache.zero_()
        layer.attention.v_cache.zero_()

@torch.no_grad()
def compare_prefill(model, x):
    # Compare full forward (no cache) vs full forward (cache prefill)
    model.eval()
    zero_all_caches(model)
    y_slow, _ = model(x, start_posn=0, use_kv_cache=False)

    zero_all_caches(model)
    y_fast, _ = model(x, start_posn=0, use_kv_cache=True)

    return (y_slow - y_fast).abs().max().item()

@torch.no_grad()
def compare_decode_one_step(model, x):
    # Prefill cache once, then compare next-token logits slow vs fast for ONE step.
    model.eval()
    zero_all_caches(model)

    # prefill cache
    _ = model(x, start_posn=0, use_kv_cache=True)

    # slow next-token logits (full context)
    slow, _ = model(x, start_posn=0, use_kv_cache=False)
    slow_next = slow[:, -1, :]

    # fast next-token logits (last token only)
    start_posn = x.shape[1] - 1
    fast, _ = model(x[:, -1:], start_posn=start_posn, use_kv_cache=True)
    fast_next = fast[:, -1, :]

    return (slow_next - fast_next).abs().max().item()

@torch.no_grad()
def layerwise_prefill_attention_diff(model, x):
    # Finds which layer’s ATTENTION output diverges on prefill
    model.eval()
    diffs = []

    # run no-cache, capture per-layer attention outputs
    zero_all_caches(model)
    h = model.token_embeddings(x)
    slow_attn_out = []
    for layer in model.layers:
        a = layer.attention(layer.attention_norm(h), start_posn=0, use_kv_cache=False)
        slow_attn_out.append(a)
        h = h + a
        h = h + layer.feed_forward(layer.ff_norm(h))[0]

    # run cache-prefill, capture per-layer attention outputs
    zero_all_caches(model)
    h = model.token_embeddings(x)
    for i, layer in enumerate(model.layers):
        a = layer.attention(layer.attention_norm(h), start_posn=0, use_kv_cache=True)
        diff = (slow_attn_out[i] - a).abs().max().item()
        diffs.append(diff)
        h = h + a
        h = h + layer.feed_forward(layer.ff_norm(h))[0]

    return diffs

# ---- run ----
x = torch.randint(0, args.vocab_size, (1, 20))
print("prefill max diff:", compare_prefill(model, x))
print("decode 1-step max diff:", compare_decode_one_step(model, x))
print("layerwise prefill attention diffs:", layerwise_prefill_attention_diff(model, x))


prefill max diff: 0.0
decode 1-step max diff: 2.5331974029541016e-07
layerwise prefill attention diffs: [0.0, 0.0]


In [20]:
import torch.nn.functional as F

# 1. Setup
# torch.manual_seed(42)
curr_seq_len = 20
x_test = torch.randint(args.vocab_size, (args.batch_size, curr_seq_len))

# 2. Forward Pass
_, all_router_logits = model(x_test)

# 3. Analyze Layer 0 (The most sensitive layer)
# logits shape: (batch_size, seq_len, num_experts)
layer0_logits = all_router_logits[0] 

# Convert to probabilities
probs = F.softmax(layer0_logits, dim=-1) 

# Average probability assigned to each expert across the whole batch
# shape: (num_experts,)
avg_expert_prob = probs.mean(dim=(0, 1)) 

print("Average Expert Probabilities:", avg_expert_prob.tolist())

# 4. Assertions
# A. No Expert Collapse: No single expert should have > 50% probability (for N=4)
# With sigma=0.02, it should be very close to 0.25
assert torch.all(avg_expert_prob < 0.4), "FAIL: Router is biased! One expert is dominating."

# B. Uniformity: The probabilities should be roughly equal (approx 1/Num_Experts)
expected_prob = 1.0 / args.num_experts
tolerance = 0.05 # Allow small variance

assert torch.all(torch.abs(avg_expert_prob - expected_prob) < tolerance), \
    f"FAIL: Router not uniform. Expected ~{expected_prob}, got {avg_expert_prob}"

print("SUCCESS: Router initialization is stable and uniform.")

Average Expert Probabilities: [0.25141024589538574, 0.24785764515399933, 0.2505405843257904, 0.25019150972366333]
SUCCESS: Router initialization is stable and uniform.
